### ISSUE TITLE
Bug Searching DPUL for "Antioch"

### ISSUE THREAD

**Issue by tampakis** [pulibrary/discoveryutils#150]
Not sure what's going on here, but when I search for "Antioch" in the [all search](https://library.princeton.edu/find/all/antioch) the [digital library response](https://library.princeton.edu/find/all/antioch#catalog_block-catalog_pudl_results) returns a "results are not available" message even though there are [results in DPUL](https://dpul.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=antioch).

**Comment by kevinreiss** [comment]
Hmm, appears to be failing parsing this key from one of the returned documents: https://library.princeton.edu/utils/dpulsearch/any?query=antioch. Strange because when I look at the json results this app pulls https://dpul.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=antioch&format=json that key is populated for all of the returned docs.
